version: '2'
networks:
  backend:
    driver: bridge
    ipam: 
      config: 
        - subnet: 172.18.0.0/16
services: 
  datagrid:
    image: jboss/infinispan-server
    container_name: datagrid
    ports:
      - "7800:7800"
      - "11221:11221"
      - "11222:11222"
      - "45700:45700"
      - "57600:57600"
    networks:
      backend:
        ipv4_address: 172.18.0.2
    extra_hosts: 
      - "localhost:172.18.0.2"
  loader:
    build: ./loader
    container_name: loader
    image: loader:1.12
    ports:
      - "8181:8181"
    networks:
      backend:
        ipv4_address: 172.18.0.3
    extra_hosts: 
      - "localhost:172.18.0.3"
    volumes:
      - "~/volume/configs:/opt/loader/configs"
      - "~/volume/logs/loader:/opt/loader/log"
    depends_on:
      - datagrid
  jboss:
    build: ./jboss
    container_name: jboss
    image: jboss:1.27
    ports:
      - "8080:8080"
      - "9990:9990"
      - "8787:8787"
    networks:
      backend:
        ipv4_address: 172.18.0.4
    extra_hosts: 
      - "localhost:172.18.0.4"
    volumes:
      - "~/volume/deployments:/opt/jboss/wildfly/standalone/deployments"
      - "~/volume/logs/jboss:/opt/jboss/wildfly/standalone/log"
    depends_on:
      - loader
